version: '3.9'

services:
  mysql:
    image: mysql:8.0.43-debian
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:7.0
    container_name: mongodb-container
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

volumes:
  mysql_data:
  mongodb_data:
