export default () => ({
  MYSQL_ROOT_PASSWORD: process.env.MYSQL_ROOT_PASSWORD,
  MYSQL_DATABASE: process.env.MYSQL_DATABASE,
  MYSQL_USER: process.env.MYSQL_USER,
  MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
  MYSQL_HOST: process.env.MYSQL_HOST,
  MYSQL_PORT: process.env.MYSQL_PORT,
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
  ACCESSTOKEN_COOKIE_EXPIRES_IN: process.env.ACCESSTOKEN_COOKIE_EXPIRES_IN,
  MONGODB_URI: process.env.MONGODB_URI,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  RESEND_EMAIL: process.env.RESEND_EMAIL,
});
